name: Main

on:
  push:
    branches:
      - master

jobs:
  main:
    runs-on: ubuntu-latest
    environment: main
    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
    - uses: actions/setup-go@4b73464bb391d4059bd26b0524d20df3927bd417 # v6.3.0
      with:
        go-version-file: 'go.mod'
        cache: true
    - id: auth
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v3'
      with:
        credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'
    - name: Run CI
      run: go run bootstrap.go ci
