name: Main

on:
  push:
    branches:
      - master

jobs:
  main:
    runs-on: ubuntu-latest
    environment: main
    steps:
    - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
    - uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6.5.0
      with:
        go-version-file: 'go.mod'
        cache: true
    - id: auth
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v3'
      with:
        credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'
    - name: Run CI
      run: go run bootstrap.go ci
